FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5051

CMD ["gunicorn", "--workers", "3", "--bind", "0.0.0.0:5051", "app:app"]
